build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:latest"
  amd64: "ghcr.io/home-assistant/amd64-base:latest"
  armv7: "ghcr.io/home-assistant/armv7-base:latest"

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Claude Terminal"
  org.opencontainers.image.description: "Terminal interface for Anthropic's Claude Code CLI"
  org.opencontainers.image.source: "https://github.com/weiting-tw/home-assistant-addons"
  org.opencontainers.image.licenses: "MIT"